# Generated by Django 3.0 on 2019-12-10 15:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('PID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.BigAutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=20)),
                ('Middle_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.CharField(max_length=10)),
                ('Type', models.CharField(default='Developer', max_length=10)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TID', models.CharField(max_length=10)),
                ('Postion', models.CharField(max_length=50)),
                ('DID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs.User')),
            ],
            options={
                'unique_together': {('TID', 'DID')},
            },
        ),
        migrations.CreateModel(
            name='Project_Status',
            fields=[
                ('PS_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Status', models.TextField()),
                ('Date_Time', models.DateTimeField(default=datetime.datetime(2019, 12, 10, 15, 55, 52, 233472))),
                ('Completed_Precentage', models.FloatField(default=0.0)),
                ('Remaining_Precentage', models.FloatField(default=100.0)),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='TID',
            field=models.ForeignKey(on_delete=django.db.models.fields.NullBooleanField, to='cs.Team'),
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('CID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Complaint', models.TextField()),
                ('Date_Time', models.DateTimeField(default=datetime.datetime(2019, 12, 10, 15, 55, 52, 233867))),
                ('Action_Taken', models.TextField(default=None)),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs.User')),
            ],
        ),
    ]
